=== MateuszDobry/HobbySite/MySite/XMLSchema1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
	
	<xs:element name="strona" type="Strona_type"/>
	<xs:complexType name="Strona_type">
		<xs:sequence>
			<xs:element name="hobbys" type="Hobbys_type"/>
			<xs:element name="informations" type="Informations_type"/>
			<xs:element name="interactions">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="interaction" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>							
									<xs:element ref="name"/>	
							</xs:sequence>
								<xs:attribute ref="mocna"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="formularz" type="Formularz_type"/>
			<xs:element name="Galleria" type="Galeria_type"/>
			<xs:element name="DaneKontaktowe">
				<xs:complexType >
					<xs:sequence>
						<xs:element name="introduction" type="xs:string"/>
						<xs:element name="formularz" type="Formularz_type"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element >
			<xs:element name="zakonczenie" type="zakonczenie_type"/>
		</xs:sequence>
			
	</xs:complexType>

	<xs:complexType name="zakonczenie_type">
		<xs:sequence>
			<xs:element ref="name"/>
		</xs:sequence>
		<xs:attribute ref="data"/>
	</xs:complexType>

	<xs:attribute name="data">
		<xs:simpleType>
			<xs:restriction base="xs:gYear"/>
		</xs:simpleType>
	</xs:attribute>

	<xs:complexType name="Informations_type">
		<xs:sequence>
			<xs:element name="information" type="Information_type" maxOccurs="unbounded"/>
			<xs:element name="extraInformation" type="Extra_informations_type" maxOccurs="unbounded"/>
		</xs:sequence>
		
	</xs:complexType>

		<xs:complexType name="Information_type">
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="description" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="extra">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="yes"/>
						<xs:enumeration value="no"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>

	<xs:complexType name="Extra_informations_type">
		<xs:complexContent>
			<xs:extension base="Information_type">
				<xs:sequence>
					<xs:element name="link" type="link_type"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="link_type">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="source" type="xs:anyURI" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
	
	<xs:element name="name" type="xs:string"/>

	<xs:complexType name="Hobbys_type">
		<xs:sequence>
			<xs:element name="hobby" type="Hobby_type" minOccurs="0" maxOccurs="3"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Hobby_type">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="image">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="title" type="xs:string"/>		
					</xs:sequence>	
				<xs:attribute name="source" type="xs:anyURI"/>
			</xs:complexType>
		</xs:element>
		</xs:sequence>
	</xs:complexType>
	


	<xs:complexType name="Formularz_type">
		<xs:sequence>
			<xs:element name="element" type="Element_type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="długi" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="Element_type">
		<xs:sequence>
			<xs:element name="name" type="Name_type"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="Name_type">
		<xs:restriction base="shortStringType">
			<xs:minLength value="3"/>
			<xs:maxLength value="100"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="shortStringType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="100"/>
        </xs:restriction>
    </xs:simpleType>



	<xs:attribute name="mocna">
		<xs:simpleType>
			<xs:restriction base="yes_no_type">
				<xs:enumeration value="yes"/>
				<xs:enumeration value="no"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

	<xs:simpleType name="yes_no_type">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="3"/>
        </xs:restriction>
    </xs:simpleType>

	<xs:complexType name="Galeria_type">
		<xs:sequence>
			<xs:element name="image" type="Galeria_image_type" maxOccurs="6"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Galeria_image_type">
		<xs:attribute name="temat" type="temat_type">
		</xs:attribute>
		<xs:attributeGroup ref="grupa"/>
	</xs:complexType>

	<xs:simpleType name="temat_type">
				<xs:restriction base="Shortstring_type">
					<xs:enumeration value="Taniec"/>
					<xs:enumeration value="Perkusja"/>
					<xs:enumeration value="Gotowanie"/>
				</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="Shortstring_type">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>

	<xs:attributeGroup name="grupa">
		<xs:attribute name="numer" type="numer_type"/>
		<xs:attribute ref="mocna" use="optional"/>
		<xs:attribute name="source" type="xs:anyURI"/>
	</xs:attributeGroup>

	<xs:simpleType name="numer_type">
	<xs:restriction base="xs:integer">
		<xs:minInclusive value="1"/>
		<xs:maxInclusive value="6"/>
	</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== MateuszDobry/HobbySite/MySite/hobby.xml
<?xml version="1.0" encoding="UTF-8"?>
<strona xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./XMLSchema1.xsd">
    <hobbys>
        <hobby>
            <name>Taniec Towarzyski</name>
            <description>Tańcem Towarzyskim zajmuję się od5rokużycia.Uwielbiamtorobićwięcnatreningiuczęszczam3razywtygodniu.Jesttodlamniepołączeniezdrowegotrybużyciaorazdobrejzabawy.</description>
            <image source="https://cdn.galleries.smcloud.net/t/galleries/gf-yARg-7Dko-6Eox_taniec-towarzyski-podzial-i-charakterystyka-tancow-towarzyskich-1920x1080-nocrop.jpg">
                <title>PassoDoble</title>
            </image>
        </hobby>
        <hobby>
            <name>Perkusja</name>
            <description>NaPerkusjigramjużod12lat.Jesttoponiekąduzupełnieniemojegotańcawktórymmuzykarównieżodgrywaważnąrolę.</description>
            <image source="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8oJMw1rc8DDv6cF2u-nBFPYE_RXHoI2SZmAAU">
                <title>Perkusja</title>
            </image>
        </hobby>
        <hobby>
            <name>Gotowanie</name>
            <description>Gotowaniemzajmujęsięrównieżodnajmłodszego.Chwilespędzoneprzytymsądlamnieczymśodkrywczymjakismacznym:).</description>
            <image source="https://kuchnialidla.pl/img/PL/587x330/28f1eb77911c-39dc8d46cbba-kw42-lidl-homar-w-sosie-maslano-pomaranczowym-z-marynowana-kapusta-stozkowa.webp">
                <title>Smażony Homar</title>
            </image>
        </hobby>
    </hobbys>
    <informations>
        <information extra="no">
            <name>Taniectowarzyski</name>
            <description>Mojeulubionezajęcieorazsportktóryuprawiamod12lat</description>
        </information>
        <information extra="no">
            <name>Perkusja</name>
            <description>Coścouwielbiamrobićwwolnymczasie.Wtymrokukończę2stopieńszkołymuzycznej.</description>
        </information>
        <information extra="no">
            <name>Gotowanie</name>
            <description>Gotowaćlubiębardzoponieważlubięjeśćdobrejedzenie.</description>
        </information>
        <extraInformation extra="yes">                           
               <name>Taniec</name>
               <description>InformacjęotańcuTowarzyskim</description>
                 <link source="https://pl.wikipedia.org/wiki/Taniec_towarzyski" ></link>
            </extraInformation>
            <extraInformation extra="yes">
                <name>Perkusja</name>
                <description>InformacjęnatematPerkusji</description>
                <link source="https://pl.wikipedia.org/wiki/Perkusja" ></link>
            </extraInformation>
            <extraInformation extra="yes">
                <name>Gotowanie</name>
                <description>InformacjęnatematPerkusji</description>
                <link source="https://www.mojegotowanie.pl/artykul/8-krokow-do-tego-by-gotowac-lepiej" ></link>
            </extraInformation>
    </informations>
    <interactions>
        <interaction mocna="no">
            <name>Zmianakolorutła</name>
        </interaction>
        <interaction mocna="yes">
            <name>Resizable</name>
        </interaction>
        <interaction mocna="yes">
            <name>Draggable</name>
        </interaction>
        <interaction mocna="no">
            <name>Przejdźnagóręstrony</name>
        </interaction>
    </interactions>
    <formularz długi="yes">
        <element>
            <name>Imię</name>
        </element>
        <element>
            <name>Nazwisko</name>
        </element>
        <element>
            <name>Płeć</name>
        </element>
        <element>
            <name>Przedział wiekowy</name>
        </element>
        <element>
            <name>Ulubione hobby</name>
        </element>
        <element>
            <name>Ulubione instrumenty</name>
        </element>
        <element>
            <name>O czym użytkownik chce więcej usłyszeć</name>
        </element>
        <element>
            <name>Ulubione danie</name>
        </element>
        <element>
            <name>Opinia użytkownika</name>
        </element>
        <element>
            <name>Wgranie plików</name>
        </element>
        <element>
            <name>Zatwierdź</name>
        </element>
        <element>
            <name>Resetuj</name>
        </element>
    </formularz>
    <Galleria>
        <image temat="Taniec" numer="1" source="https://scontent.fpoz4-1.fna.fbcdn.net/v/t1.15752-9/368359542_6991113584282517_6336954450948896957_n.jpg?_nc_cat=109=8cd0a2=7tS8emvQzwIAX9S3aI=scontent.fpoz4-1.fnaAdQMzNF3R4LHDCoQMhowi7atU2KNrmIfJZtg0h0NJH8kQw"/>
        <image temat="Taniec" numer="2" source="https://scontent.fpoz4-1.fna.fbcdn.net/v/t1.15752-9/368099466_815712853663669_7152934114617225867_n.jpg?_nc_cat=109=8cd0a2=GG9HG9vzuWIAX8MxJw=scontent.fpoz4-1.fna"/>
        <image temat="Taniec" numer="3" source="https://scontent.fpoz4-1.fna.fbcdn.net/v/t1.15752-9/371510771_558916039736334_6547397836796777977_n.jpg?_nc_cat=102=8cd0a2_X7qDKMAX_qOED5=scontent.fpoz4-1.fna"/>
        <image temat="Perkusja" numer="4" source="./Assets/perkusja.webp"/>
        <image temat="Perkusja" numer="5" source="./Assets/marimba.jpg"/>
        <image mocna="no" temat="Gotowanie" numer="6" source="./Assets/brownie.jpg"/>
    </Galleria>
    <DaneKontaktowe>
        <introduction> Zapraszam do kontaktu ze mną za pomocą tego e-maila: mateusz.dobry5@wp.pl</introduction>
        <formularz>
            <element>
                <name>Podaj e-mail</name>
            </element>
        </formularz>
    </DaneKontaktowe>
    <zakonczenie data="2023">
        <name>Mateusz</name>
    </zakonczenie>
</strona>
